language: node_js
node_js:
- '5'
notifications:
  email: false
  slack:
    secure: V4wAm8r5FFcnHOEf8dufSxJy5IYI0mzakAVAMyq1tbUbjfPabA/xj+fITnYt4UyzxWGALskIl8mGjwtU2fnfiRRpMY6QVbbCn+B5UkBtOAgbYl2ut6mra5kMx/+/4PGChwrSfTSsHkBlTy5Cg3VWtOqTGRAW3SWPFbkrbR6hpYvH72Vld5SIC9soDAsBmkKStAPtjK82zQ9y7n8cnCkAfZ3SqgJ8cLqFGWrFtujSw5Xq77FVlkQEG1D5lDuj32yFbfEwB9/djv9fUZGNPzWnRYrPlDDSG9iQzNT46lPY8GPRPzhrPEAwylPNyh6Bdl+8MZ1ri9qevk4Rfj5Zoh7lrK8H4cED3ifZaJMeEQ0SpaDfCCB8KTRHXIpP8SsCEyVE6WLo57W5nrs1lzgHxBeCLVmk41S1Nc2R0gA9c/2Lp5wQj0Zt3WHIUTmUqvUKkNU60QYyXovEYG/9FQMSiMiN1OxmS/8HpR6yzFqwZAx+mILG5MLOshZj5ay0uzmgRS3lIckKMNslod1P1PE4R6KW42tQaVJ4ib+VStxJYjzXt6iFkGy7qGrqEIzuEIT9Zxb+J2G2UXug4huUAYmV1WBbBna6VKNQDP9jiLQe7QPKbOaozdVy5WLOKmC3a10NlpGsBlC2U660ljmBLA6i6oI/53D/7xqEkP3rDQXXVGuujQI=
