language: node_js
node_js:
- '5'
sudo: required
before_install:
- npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email: false
  slack:
    secure: WK6Zk2lSqGLB6Hf4J2MOMjPWtDjQwXFJoSapX7mZfRq8ya2wISbmtnjO2pg9g1yKKM9CYgVzJ63NIBk2h9Jhv8EwrNrRGcRyxihTImhQJkCKMjIiYlTD4mR2FAIL7OAyeZgIvdYp7Js4pHUO9T9mRRop04rRq04KOBxywCshUViUcw2r4hQNELB3T/TlZ7hhIXZnosZ4QKPq2vQ0F+K8aZuWca+Zvq5GcRaKdoU+OjOy3ZpLjT9US7JuOB5XtDtHbWgS22QQ0DFg0fBhf2KJrcZ6oyH7gC8ZiRvH2MVyqjUORKw+8Pk0rtjDPeRypspR++mLZsOIA5qzXPEZpsNyitvwLCd6o+YVT0VoONiIXWxKPoCIwE1o0TVdG4ClD/Td8qOVmj4uvM0Jh8U7xNsDAq0xy/Eosr+gWXMVrRGPrWUs87BtL66mtY54MbKyJrLVtkTn4TS5Q5FgHrNzaRsY2qo+IRg1noV8MaVsaRpwTgu2vTeqEdkm2bwWGXPVmRPB9Jm5QM/R5S7flF0IDWrN+m8ZM8GuJS3EFxYuRstPgT8u3dWPYna2vFcnAlW/WTl9LTDJWlBgvj62Hrd9vudKWfO6ZCintqpJfPvLjpvw1/EYpeylVseG/4nIY3CqCx/e2kQWyWu8zwlDSdchGdAcli6PG+jNFUPtivtGSt8rEGI=
after_success:
- sh ./scripts/publish-docs-and-examples.sh
- npm run coverage
env:
  matrix:
    secure: I3hjR+BBPHlGBnxPCu+ey/6PuPRVsbyTSUyi09DDDTIa0SWhubvZgac2UQW9IJHY5jz5EOXOmk2nf9khGlz0pJdFsr3wyHbpFoTYmW2ns2EpqtqHLiz+4sQP4PQ3XZ6WdtRt63RkLYCaFMq6QHtHtpQP4kanWSuhqV6tUgjho1mZjXOEyY2/YcfVpVd0pa6u+S5/0WJEba3l0zBYkzyTp2WtiAGte0fYvO/5Q/vlWBUkE+zIsROpFVCP8yv29jwolsoH0a/v/sEOWglwIOU5ntyInir31edVVwiG4hGT8LBYG0JZbJlJyJvudZ68I9pB5ThdFsUZKOHWADwIhzD1EFOPXR/bPDuoEC/F3mOYbDm03GADHianQrYbIaupl+i8MnCJXDZFshrbtekOwvz56tOp31IZePR6EFAJOiwTejFdel09C01bWY7Yq4y5udOcNcWj6yUCLxTUKOVFM/JuySfZavdz4NhscfyrGPpXbsGMq0sR17EjFRRPPNq5aZ2mnpMG4q59rkdKHBzO6WPLHplD3EVjiZA0N6MgXktKBrsBjRJ/FjVzEz263wV5J7iY2h1RcgXPrJRM9JfQTd9XRxw4RH6yA4Gi9AMv6pG7m4uaLzagdmuiAp7Q9sn4s+d7vM43p9FDOpWXO7U+UO49xZ8zantY6oYXnfzCpXZTsKY=
